features:
  versions:
    - HTTP_VERSION_1
    - HTTP_VERSION_2
  protocols:
    - PROTOCOL_CONNECT
  codecs:
    - CODEC_PROTO
    - CODEC_JSON
  compressions:
    - COMPRESSION_IDENTITY
    - COMPRESSION_GZIP
  stream_types:
    - STREAM_TYPE_UNARY
    - STREAM_TYPE_CLIENT_STREAM

  supports_trailers: false
  supports_tls: true
  supports_tls_client_certs: true
  supports_half_duplex_bidi_over_http1: false
  supports_h2c: true
  supports_connect_get: true
  supports_message_receive_limit: false
