features:
  versions:
    - HTTP_VERSION_1
    - HTTP_VERSION_2
  protocols:
    # - PROTOCOL_CONNECT
    - PROTOCOL_GRPC
  codecs:
    - CODEC_PROTO
    # - CODEC_JSON
  compressions:
    # - COMPRESSION_IDENTITY
    - COMPRESSION_GZIP
  stream_types:
    - STREAM_TYPE_UNARY
    # - STREAM_TYPE_CLIENT_STREAM
    # - STREAM_TYPE_SERVER_STREAM
    # - STREAM_TYPE_HALF_DUPLEX_BIDI_STREAM

  supports_trailers: true
  supports_tls: false
  supports_tls_client_certs: false
  supports_half_duplex_bidi_over_http1: true
  supports_h2c: true
  supports_connect_get: true
  supports_message_receive_limit: false
