"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2022-2023 The Connect Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class SayRequest(google.protobuf.message.Message):
    """SayRequest is a single-sentence request."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SENTENCE_FIELD_NUMBER: builtins.int
    sentence: builtins.str
    def __init__(
        self,
        *,
        sentence: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["sentence", b"sentence"]) -> None: ...

global___SayRequest = SayRequest

@typing.final
class SayResponse(google.protobuf.message.Message):
    """SayResponse is a single-sentence response."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SENTENCE_FIELD_NUMBER: builtins.int
    sentence: builtins.str
    def __init__(
        self,
        *,
        sentence: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["sentence", b"sentence"]) -> None: ...

global___SayResponse = SayResponse
