# Generated by the protoc-gen-connect-python. DO NOT EDIT!
# source: examples/proto/connectrpc/eliza/v1/v1connect/eliza.proto
# Protobuf Python Version: v5.29.2
# protoc-gen-connect-python version: (devel)
"""Generated connect code."""

import abc
from enum import Enum

from google.protobuf.descriptor import MethodDescriptor, ServiceDescriptor

from connect.handler import UnaryHandler
from connect.request import ConnectRequest
from connect.response import ConnectResponse
from connectrpc.eliza.v1 import eliza_pb2
from connectrpc.eliza.v1.eliza_pb2 import SayRequest, SayResponse


class ElizaServiceProcedures(Enum):
    """Procedures for the eliza service."""

    Eliza = "/connectrpc.eliza.v1.ElizaService/Eliza"


ElizaService_service_descriptor: ServiceDescriptor = eliza_pb2.DESCRIPTOR.services_by_name["ElizaService"]

ElizaService_Ping_method_descriptor: MethodDescriptor = ElizaService_service_descriptor.methods_by_name["Eliza"]


class ElizaServiceHandler(metaclass=abc.ABCMeta):
    """Handler for the eliza service."""

    @abc.abstractmethod
    async def Eliza(self, request: ConnectRequest[SayRequest]) -> ConnectResponse[SayResponse]: ...


def create_ElizaService_handler(service: ElizaServiceHandler) -> list[UnaryHandler]:
    rpc_handlers = [
        UnaryHandler(
            ElizaServiceProcedures.Eliza.value,
            service.Eliza,
            SayRequest,
            SayResponse,
        )
    ]
    return rpc_handlers
