# Generated by the protoc-gen-connect-python. DO NOT EDIT!
# source: examples/proto/connectrpc/eliza/v1/v1connect/eliza.proto
# Protobuf Python Version: v5.29.2
# protoc-gen-connect-python version: (devel)
"""Generated connect code."""

import abc
from enum import Enum

from connect.connect import ConnectRequest, ConnectResponse
from connect.handler import UnaryHandler
from connect.options import ConnectOptions
from connectrpc.eliza.v1 import eliza_pb2
from connectrpc.eliza.v1.eliza_pb2 import SayRequest, SayResponse
from google.protobuf.descriptor import MethodDescriptor, ServiceDescriptor


class ElizaServiceProcedures(Enum):
    """Procedures for the eliza service."""

    Say = "/connectrpc.eliza.v1.ElizaService/Say"


ElizaService_service_descriptor: ServiceDescriptor = eliza_pb2.DESCRIPTOR.services_by_name["ElizaService"]

ElizaService_Say_method_descriptor: MethodDescriptor = ElizaService_service_descriptor.methods_by_name["Say"]


class ElizaServiceHandler(metaclass=abc.ABCMeta):
    """Handler for the eliza service."""

    @abc.abstractmethod
    async def Say(self, request: ConnectRequest[SayRequest]) -> ConnectResponse[SayResponse]: ...


def create_ElizaService_handler(
    service: ElizaServiceHandler, options: ConnectOptions | None = None
) -> list[UnaryHandler]:
    rpc_handlers = [
        UnaryHandler(
            procedure=ElizaServiceProcedures.Say.value,
            unary=service.Say,
            input=SayRequest,
            output=SayResponse,
            options=options,
        )
    ]
    return rpc_handlers
