# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ping/v1/ping.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'ping/v1/ping.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12ping/v1/ping.proto\x12\x07ping.v1\"\x1b\n\x0bPingRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\x0cPingResponse\x12\x0c\n\x04name\x18\x01 \x01(\t2D\n\x0bPingService\x12\x35\n\x04Ping\x12\x14.ping.v1.PingRequest\x1a\x15.ping.v1.PingResponse\"\x00\x42\x1f\n\x07ping.v1B\tGingProtoP\x01Z\x07ping/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ping.v1.ping_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\007ping.v1B\tGingProtoP\001Z\007ping/v1'
  _globals['_PINGREQUEST']._serialized_start=31
  _globals['_PINGREQUEST']._serialized_end=58
  _globals['_PINGRESPONSE']._serialized_start=60
  _globals['_PINGRESPONSE']._serialized_end=88
  _globals['_PINGSERVICE']._serialized_start=90
  _globals['_PINGSERVICE']._serialized_end=158
# @@protoc_insertion_point(module_scope)
